---
title: "Modelisation et décomposition d'Oaxaca avec définition 'souple' de la mauvaise santé"
author: "Thomas Laurent"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE,message=FALSE)
```


```{r}
###Libraries###
library(haven)
library(tidyverse)
library(readxl)
library(forcats)
library(kableExtra)
library(sampleSelection)
library(margins)
library(ggplot2)
library(ggthemes)
library(RColorBrewer)
library(devEMF)
```

```{r}
###Data import###
elders=haven::read_sas("/Users/thomaslaurent/Documents/Cours-M2/Memoire/Project/file_180505/elders_180505.sas7bdat",catalog_file="//Users/thomaslaurent/Documents/Cours-M2/Memoire/Project/file_180505/formats.sas7bcat",encoding="latin1")

##Conversion en factor
#Lecture du fichier d'annotation
annot=read_excel("/Users/thomaslaurent/Documents/Cours-M2/Memoire/Project/file_180505/Variable_Dataset_cleaned.xlsx")
```

```{r}
###Conversion en factor et definition des niveaux de reference###

modeldata=elders %>% 
  mutate(age_classe=droplevels(as_factor(age_classe))) %>% 
  mutate(etude_c=droplevels(as_factor(etude_c))) %>% 
  mutate(revucinsee_c=droplevels(as_factor(revucinsee_c))) %>% 
  mutate(CC=droplevels(as_factor(CC)))%>% 
  mutate(risque_c=droplevels(as_factor(risque_c))) %>% 
  mutate(alcool_c=droplevels(haven::as_factor(alcool_c))) %>% 
  mutate(COUPLE_c=droplevels(as_factor(COUPLE_c))) %>% 
  mutate(difpayer_c=droplevels(as_factor(difpayer_c))) %>% 
  mutate(fum_cat=droplevels(as_factor(fum_cat))) %>% 
  mutate(TPS_c=droplevels(as_factor(TPS_c))) %>% 
  mutate(etasante_g=droplevels(as_factor(etasante_g))) %>% 
  mutate(RENONC_FLG=droplevels(as_factor(RENONC_FLG))) %>% 
  mutate(homme=droplevels(as_factor(homme))) %>% 
  mutate(etasante_g=forcats::fct_recode(etasante_g,
                               "Poor"="Tres mauvais",
                               "Poor"="Mauvais",
                               "Poor"="Assez Bon",
                               "Good"="Bon",
                               "Good"="Tres bon")) %>% 
  mutate(age_classe=forcats::fct_recode(age_classe,
                               "65-69 \n Years"="65-69",
                               "70-74 \n Years"="70-74",
                               "75-79 \n Years"="75-79",
                               "80-84 \n Years"="80-84",
                               "85+ \n Years"="85-89",
                               "85+ \n Years"="90+")) %>%
  mutate(etasante_g=relevel(etasante_g,ref="Good")) %>% 
  mutate(RENONC_FLG=relevel(RENONC_FLG,ref="Non")) %>% 
  mutate(difpayer_c=relevel(difpayer_c,ref="Non")) %>% 
    mutate(COUPLE_c=relevel(COUPLE_c,ref="Non")) %>% 
  mutate(renonc_gen=droplevels(as_factor(renonc_gen))) %>% 
  mutate(renonc_gen=relevel(renonc_gen,ref="Non")) %>% 
  mutate(renonc_gp=droplevels(as_factor(renonc_gp))) %>% 
  mutate(renonc_gp=relevel(renonc_gp,ref="Non")) %>% 
  mutate(renonc_spe=droplevels(as_factor(renonc_spe))) %>% 
  mutate(renonc_spe=relevel(renonc_spe,ref="Non")) %>% 
  mutate(risque_c=relevel(risque_c,ref="Prise de risque")) %>% 
  mutate(fragilite_code=factor(ifelse(fragilite>=3,1,0))) %>% 
  mutate(etatsante_factor=factor(etasante_x)) %>% 
  mutate(fum_cat=relevel(fum_cat,ref="Ne fume pas")) %>% 
  mutate(CMU_x=droplevels(as_factor(CMU_x))) %>% 
  mutate(CMU_x=relevel(CMU_x,ref="Non")) %>% 
  mutate(CC_x=droplevels(as_factor(CC_x))) %>% 
  mutate(CC_x=relevel(CC_x,ref="Non")) %>% 
  mutate(CSP_cat=droplevels(as_factor(CSP_cat))) %>% 
  mutate(ISOLEMENT_c=droplevels(as_factor(ISOLEMENT_c))) %>% 
  mutate(ISOLEMENT_c=relevel(ISOLEMENT_c,ref="Non")) %>% 
  mutate(renonc_flg_all=droplevels(as_factor(renonc_flg_all))) %>% 
  mutate(renonc_flg_all=relevel(renonc_flg_all,ref="Non")) %>% 
  mutate(fragilite_cat=droplevels(as_factor(fragilite))) %>% 
  mutate(fragilite_cat=forcats::fct_recode(fragilite_cat,
                                           "Robust"="0",
                                           "Pre-frail"="1",
                                           "Pre-frail"="2",
                                           "Frail"="3",
                                           "Frail"="4",
                                           "Frail"="5")) %>% 
  mutate(alcool_num=as.numeric(alcool_c)) %>% 
  mutate(alcool_cat=factor(alcool_num,
                              labels=c("Jamais","1 fois par mois ou moins",
                                       "2 a 4 fois par mois"))) %>% 
  mutate(TPSAMI_x=droplevels(as_factor(TPSAMI_c))) %>% 
  mutate(TPSASSO_x=droplevels(as_factor(TPSASSO_c))) %>% 
  mutate(TPSFAMIL_x=droplevels(as_factor(TPSFAMIL_c))) %>% 
  mutate(TPS=ifelse(TPSAMI_x %in% c("Tous les jours ou presque","Au moins une fois par semaine") |
                              TPSASSO_x %in% c("Tous les jours ou presque","Au moins une fois par semaine") |
                                                        TPSFAMIL_x %in% c("Tous les jours ou presque","Au moins une fois par semaine"),3,ifelse(TPSASSO_x %in% c("Au moins une fois par mois","Moins d'une fois par mois") |
                              TPSAMI_x %in% c("Au moins une fois par mois","Moins d'une fois par mois") |
                                                        TPSFAMIL_x %in% c("Au moins une fois par mois","Moins d'une fois par mois"),2,1))) %>% 
  mutate(TPS=factor(TPS,labels=c("Jamais","Moyen","Beaucoup"))) %>% 
  mutate(taille_ville=as_factor(taille_ville)) %>% 
  mutate(taille_ville=relevel(taille_ville,ref="Tres grande")) %>% 
  mutate(taille_ville2=as_factor(taille_ville2)) %>% 
  mutate(taille_ville2=relevel(taille_ville2,ref="Grande")) %>% 
  mutate(pole=as_factor(pole)) %>% 
  mutate(pole=relevel(pole,ref="Grand pole")) %>% 
  mutate(verre=as_factor(verre)) %>% 
  mutate(verre=relevel(verre,ref="Jamais")) %>% 
  mutate(verre=fct_recode(verre,
                          "Never"="Jamais",
                          "Less than one glass a week",
                          "More than one glass"="1 verre",
                          "More than one glass"="Plus d'un verre")) %>% 
  mutate(TPS=relevel(TPS,ref="Beaucoup")) %>% 
  mutate(social=as_factor(social)) %>% 
  mutate(PBPATHOL_classe=factor(ifelse(PB_PATHOL<=1,1,2),labels=c("0-1","More than one"))) %>% 
  mutate(AVENIR_classe=factor(ifelse(AVENIR<=6,1,2),labels=c("Not concerned about the future","Concerned about the future"))) %>% 
  mutate(RISQUE_classe=factor(ifelse(RISQUE<=5,1,2),labels=c("Risk-averse","Risk-seeking"))) %>% 
  mutate(VISIT_RECOM=droplevels(as_factor(VISIT_RECOM))) %>% 
  mutate(VISIT_RECOM=relevel(VISIT_RECOM,ref="Non")) %>% 
  mutate(revenu_dummy=ifelse(revucinsee_c %in% c("1ere tranche","2eme tranche"),"Low","High")) %>% 
  mutate(etatsante_score=as.numeric(NOTE))
```


```{r}
#Suppression des observations avec des donnees manquantes
modeldata_sg5=subset(modeldata,!is.na(etasante_g) & DEPAMB>0 & !is.na(age_classe)
                     & !is.na(homme) & !is.na(etude_c) & !is.na(CMU_x)
                     & !is.na(CC_x) & !is.na(CSP_cat) & !is.na(fum_cat) & !is.na(verre) &
                       !is.na(difpayer_c) & !is.na(COUPLE_c) & !is.na(RISQUE_classe) &  !is.na(AVENIR_classe) & !is.na(age_classe) & !is.na(adl_limit) &  !is.na(TPS) &
                       !is.na(PBPATHOL_classe) & !is.na(etatsante_score))

#Log des depenses
modeldata_sg5=modeldata_sg5 %>%
  mutate(LOGDEP=log(DEPAMB)) %>% 
  filter(etasante_g!="0") %>% 
  droplevels()
```

```{r}
###Caracteristiques totale###
#Annotation#
annot=data.frame(label=c("Age","Gender","Socioprofessional category","Complementary healthcare insurance","Universal healthcare insurance","Financial difficulties","Income","Married","Drinking","Smoking","Risk seeking","Education","Time-preference","Experience of seclusion","Size of urban area","Social life","Self-perceived health","Number of ADL","Number of pathologies","Frailty"),
variable=c("age_classe","homme","CSP_cat","CC_x","CMU_x","difpayer_c","revenu_dummy","COUPLE_c","verre","fum_cat","RISQUE_classe","etude_c","AVENIR_classe","ISOLEMENT_c","pole","social","etasante_g","adl_limit","PBPATHOL_classe","fragilite_cat"))

```

```{r}
#Depenses par poste par tranche d'age#
mean_stat=modeldata_sg5 %>% 
  group_by(age_classe) %>% 
  summarise_at(vars(DEPOMN,DEPSPE,DEPDEN,DEPSAG,DEPINF,DEPKIN,DEPAAU,DEPBIO,DEPURG,DEPPHA,DEPMAT,DEPOPT,DEPTRA,DEPPRO,DEPSOIN_E),funs(mean)) %>% 
  gather(key,value,-age_classe) %>% 
  arrange(value)
mean_stat=mean_stat %>% 
  mutate(key=case_when(
    key=="DEPOMN" ~ "GPs",
    key=="DEPSPE" ~ "Specialists",
    key=="DEPDEN" ~ "Dentists",
    key=="DEPSAG" ~ "Sages-femme",
    key=="DEPINF" ~ "Nurses",
    key=="DEPKIN" ~ "Physiotherapists",
    key=="DEPAAU" ~ "Other auxiliaries",
    key=="DEPBIO" ~ "Biomedical analyses",
    key=="DEPURG" ~ "Emergency",
    key=="DEPPHA" ~ "Medicine",
    key=="DEPMAT" ~ "Health materials",
    key=="DEPOPT" ~ "Optics",
    key=="DEPTRA" ~ "Transport",
    key=="DEPPRO" ~ "Prosthetics",
    key=="DEPSOIN_E" ~ "Etranger"
  )) %>% 
  mutate(value=round(value,digits=0)) %>% 
  filter(!(key %in% c("Etranger","Sages-femme")))
  

gg8=ggplot(data=mean_stat,aes(x=reorder(key, -value),y=value,fill=key))+
  geom_bar(stat="identity")+
  ylab(label="Mean of healthcare expenditures (in euros)")+
  xlab(label="")+
  geom_text(aes(label=value), color="black", size=5)+
  guides(fill=FALSE)+
  scale_x_discrete()+
  theme_gdocs()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1,size=20),
        axis.text.y = element_text(size=15),
        axis.title.y = element_text(size=20),
        strip.text.y = element_text(size=20))+
  facet_grid(age_classe~.)

emf(file = "dep_poste_age.emf", width = 10, height = 7)
print(gg8)
dev.off()

```

```{r}
#Depenses en fonction du renoncement#
temp=modeldata_sg5 %>% 
    mutate(renonc_flg_all=forcats::fct_recode(renonc_flg_all,
                                            "Unmet needs \n Yes"="Oui",
                                            "Unmet needs \n No"="Non")) %>% 
           mutate(renonc_flg_all=relevel(renonc_flg_all,ref="Unmet needs \n No"))

gg17=ggplot(temp, aes(x=LOGDEP))+
  geom_histogram(aes(y=..density..),color="black",fill="#0d488a")+
  geom_density(alpha=0.6,color="#e86800")+
    facet_grid(renonc_flg_all~.)+
  xlab("Ambulatory healthcare expenditures (log)")+
  ylab("Density")+
    theme_gdocs()+
      theme(axis.text.x = element_text(size=15),
        axis.text.y = element_text(size=15),
        axis.title.y = element_text(size=20),
        axis.title.x = element_text(size=20),
        strip.text.y = element_text(size=20))

emf(file = "dep_renonc.emf", width = 10, height = 7)
print(gg17)
dev.off()
```

```{r}
#Depenses par poste en fonction du renoncement#
mean_stat=modeldata_sg5 %>%
      mutate(renonc_flg_all=forcats::fct_recode(renonc_flg_all,
                                            "Unmet needs \n Yes"="Oui",
                                            "Unmet needs \n No"="Non")) %>% 
           mutate(renonc_flg_all=relevel(renonc_flg_all,ref="Unmet needs \n No")) %>% 
  group_by(renonc_flg_all) %>% 
  summarise_at(vars(DEPOMN,DEPSPE,DEPDEN,DEPSAG,DEPINF,DEPKIN,DEPAAU,DEPBIO,DEPURG,DEPPHA,DEPMAT,DEPOPT,DEPTRA,DEPPRO,DEPSOIN_E),funs(mean)) %>% 
  gather(key,value,-renonc_flg_all) %>% 
  arrange(value)
mean_stat=mean_stat %>% 
  mutate(key=case_when(
    key=="DEPOMN" ~ "GPs",
    key=="DEPSPE" ~ "Specialists",
    key=="DEPDEN" ~ "Dentists",
    key=="DEPSAG" ~ "Sages-femme",
    key=="DEPINF" ~ "Nurses",
    key=="DEPKIN" ~ "Physiotherapists",
    key=="DEPAAU" ~ "Other auxiliaries",
    key=="DEPBIO" ~ "Biomedical analyses",
    key=="DEPURG" ~ "Emergency",
    key=="DEPPHA" ~ "Medicine",
    key=="DEPMAT" ~ "Health materials",
    key=="DEPOPT" ~ "Optics",
    key=="DEPTRA" ~ "Transport",
    key=="DEPPRO" ~ "Prosthetics",
    key=="DEPSOIN_E" ~ "Etranger"
  )) %>% 
  mutate(value=round(value,digits=0)) %>% 
  filter(!(key %in% c("Etranger","Sages-femme")))
  

gg18=ggplot(data=mean_stat,aes(x=reorder(key, -value),y=value,fill=key))+
  geom_bar(stat="identity")+
  ylab(label="Mean of healthcare expenditures (in euros)")+
  xlab(label="")+
  geom_text(aes(label=value), color="black", size=5)+
  guides(fill=FALSE)+
  scale_x_discrete()+
  theme_gdocs()+
    theme(axis.text.x = element_text(angle = 45, hjust = 1,size=20),
        axis.text.y = element_text(size=15),
        axis.title.y = element_text(size=20),
        strip.text.y = element_text(size=20))+
  facet_grid(renonc_flg_all~.)

emf(file = "dep_poste_renonc.emf", width = 10, height = 7)
print(gg18)
dev.off()
```


```{r,fig.height=7,fig.width=5}
#Depenses par niveau de fragilite#

gg4=ggplot(modeldata_sg5, aes(x=LOGDEP))+
  geom_histogram(aes(y=..density..),color="black",fill="#0d488a")+
  geom_density(alpha=0.6,color="#e86800")+
    facet_grid(fragilite_cat~.)+
  xlab("Ambulatory healthcare expenditures (log)")+
  ylab("Density")+
    theme_gdocs()+
        theme(axis.text.x = element_text(size=15),
        axis.text.y = element_text(size=15),
        axis.title.y = element_text(size=20),
        axis.title.x = element_text(size=20),
        strip.text.y = element_text(size=20))

emf(file = "dep_frailty.emf", width = 10, height = 7)
print(gg4)
dev.off()
```
