---
title: "Modelisation et décomposition d'Oaxaca avec définition 'souple' de la mauvaise santé"
author: "Thomas Laurent"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE,message=FALSE)
```


```{r}
###Libraries###
library(haven)
library(tidyverse)
library(readxl)
library(forcats)
library(kableExtra)
library(sampleSelection)
library(margins)
library(ggplot2)
library(ggthemes)
library(RColorBrewer)
```

```{r}
###Data import###
elders=haven::read_sas("/Users/thomaslaurent/Documents/Cours-M2/Memoire/Project/file_180505/elders_180505.sas7bdat",catalog_file="//Users/thomaslaurent/Documents/Cours-M2/Memoire/Project/file_180505/formats.sas7bcat",encoding="latin1")

##Conversion en factor
#Lecture du fichier d'annotation
annot=read_excel("/Users/thomaslaurent/Documents/Cours-M2/Memoire/Project/file_180505/Variable_Dataset_cleaned.xlsx")
```

```{r}
###Conversion en factor et definition des niveaux de reference###

modeldata=elders %>% 
  mutate(age_classe=droplevels(as_factor(age_classe))) %>% 
  mutate(etude_c=droplevels(as_factor(etude_c))) %>% 
  mutate(revucinsee_c=droplevels(as_factor(revucinsee_c))) %>% 
  mutate(CC=droplevels(as_factor(CC)))%>% 
  mutate(risque_c=droplevels(as_factor(risque_c))) %>% 
  mutate(alcool_c=droplevels(haven::as_factor(alcool_c))) %>% 
  mutate(COUPLE_c=droplevels(as_factor(COUPLE_c))) %>% 
  mutate(difpayer_c=droplevels(as_factor(difpayer_c))) %>% 
  mutate(fum_cat=droplevels(as_factor(fum_cat))) %>% 
  mutate(TPS_c=droplevels(as_factor(TPS_c))) %>% 
  mutate(etasante_g=droplevels(as_factor(etasante_g))) %>% 
  mutate(RENONC_FLG=droplevels(as_factor(RENONC_FLG))) %>% 
  mutate(homme=droplevels(as_factor(homme))) %>% 
  mutate(etasante_g=forcats::fct_recode(etasante_g,
                               "Poor"="Tres mauvais",
                               "Poor"="Mauvais",
                               "Poor"="Assez Bon",
                               "Good"="Bon",
                               "Good"="Tres bon")) %>% 
  mutate(age_classe=forcats::fct_recode(age_classe,
                               "65-69"="65-69",
                               "70-74"="70-74",
                               "75-79"="75-79",
                               "80-84"="80-84",
                               "85+"="85-89",
                               "85+"="90+")) %>%
  mutate(etasante_g=relevel(etasante_g,ref="Good")) %>% 
  mutate(RENONC_FLG=relevel(RENONC_FLG,ref="Non")) %>% 
  mutate(difpayer_c=relevel(difpayer_c,ref="Non")) %>% 
    mutate(COUPLE_c=relevel(COUPLE_c,ref="Non")) %>% 
  mutate(renonc_gen=droplevels(as_factor(renonc_gen))) %>% 
  mutate(renonc_gen=relevel(renonc_gen,ref="Non")) %>% 
  mutate(renonc_gp=droplevels(as_factor(renonc_gp))) %>% 
  mutate(renonc_gp=relevel(renonc_gp,ref="Non")) %>% 
  mutate(renonc_spe=droplevels(as_factor(renonc_spe))) %>% 
  mutate(renonc_spe=relevel(renonc_spe,ref="Non")) %>% 
  mutate(risque_c=relevel(risque_c,ref="Prise de risque")) %>% 
  mutate(fragilite_code=factor(ifelse(fragilite>=3,1,0))) %>% 
  mutate(etatsante_factor=factor(etasante_x)) %>% 
  mutate(fum_cat=relevel(fum_cat,ref="Ne fume pas")) %>% 
  mutate(CMU_x=droplevels(as_factor(CMU_x))) %>% 
  mutate(CMU_x=relevel(CMU_x,ref="Non")) %>% 
  mutate(CC_x=droplevels(as_factor(CC_x))) %>% 
  mutate(CC_x=relevel(CC_x,ref="Non")) %>% 
  mutate(CSP_cat=droplevels(as_factor(CSP_cat))) %>% 
  mutate(ISOLEMENT_c=droplevels(as_factor(ISOLEMENT_c))) %>% 
  mutate(ISOLEMENT_c=relevel(ISOLEMENT_c,ref="Non")) %>% 
  mutate(renonc_flg_all=droplevels(as_factor(renonc_flg_all))) %>% 
  mutate(renonc_flg_all=relevel(renonc_flg_all,ref="Non")) %>% 
  mutate(fragilite_cat=droplevels(as_factor(fragilite))) %>% 
  mutate(fragilite_cat=forcats::fct_recode(fragilite_cat,
                                           "Robust"="0",
                                           "Pre-frail"="1",
                                           "Pre-frail"="2",
                                           "Frail"="3",
                                           "Frail"="4",
                                           "Frail"="5")) %>% 
  mutate(alcool_num=as.numeric(alcool_c)) %>% 
  mutate(alcool_cat=factor(alcool_num,
                              labels=c("Jamais","1 fois par mois ou moins",
                                       "2 a 4 fois par mois"))) %>% 
  mutate(TPSAMI_x=droplevels(as_factor(TPSAMI_c))) %>% 
  mutate(TPSASSO_x=droplevels(as_factor(TPSASSO_c))) %>% 
  mutate(TPSFAMIL_x=droplevels(as_factor(TPSFAMIL_c))) %>% 
  mutate(TPS=ifelse(TPSAMI_x %in% c("Tous les jours ou presque","Au moins une fois par semaine") |
                              TPSASSO_x %in% c("Tous les jours ou presque","Au moins une fois par semaine") |
                                                        TPSFAMIL_x %in% c("Tous les jours ou presque","Au moins une fois par semaine"),3,ifelse(TPSASSO_x %in% c("Au moins une fois par mois","Moins d'une fois par mois") |
                              TPSAMI_x %in% c("Au moins une fois par mois","Moins d'une fois par mois") |
                                                        TPSFAMIL_x %in% c("Au moins une fois par mois","Moins d'une fois par mois"),2,1))) %>% 
  mutate(TPS=factor(TPS,labels=c("Jamais","Moyen","Beaucoup"))) %>% 
  mutate(taille_ville=as_factor(taille_ville)) %>% 
  mutate(taille_ville=relevel(taille_ville,ref="Tres grande")) %>% 
  mutate(taille_ville2=as_factor(taille_ville2)) %>% 
  mutate(taille_ville2=relevel(taille_ville2,ref="Grande")) %>% 
  mutate(pole=as_factor(pole)) %>% 
  mutate(pole=relevel(pole,ref="Grand pole")) %>% 
  mutate(verre=as_factor(verre)) %>% 
  mutate(verre=relevel(verre,ref="Jamais")) %>% 
  mutate(verre=fct_recode(verre,
                          "Never"="Jamais",
                          "Less than one glass a week",
                          "More than one glass"="1 verre",
                          "More than one glass"="Plus d'un verre")) %>% 
  mutate(TPS=relevel(TPS,ref="Beaucoup")) %>% 
  mutate(social=as_factor(social)) %>% 
  mutate(PBPATHOL_classe=factor(ifelse(PB_PATHOL<=1,1,2),labels=c("0-1","More than one"))) %>% 
  mutate(AVENIR_classe=factor(ifelse(AVENIR<=6,1,2),labels=c("Not concerned about the future","Concerned about the future"))) %>% 
  mutate(RISQUE_classe=factor(ifelse(RISQUE<=5,1,2),labels=c("Risk-averse","Risk-seeking"))) %>% 
  mutate(VISIT_RECOM=droplevels(as_factor(VISIT_RECOM))) %>% 
  mutate(VISIT_RECOM=relevel(VISIT_RECOM,ref="Non")) %>% 
    mutate(revenu_dummy=ifelse(revucinsee_c %in% c("1ere tranche","2eme tranche"),"Low","High")) %>% 
  mutate(etatsante_score=as.numeric(NOTE))
```


```{r}
#Suppression des observations avec des donnees manquantes
modeldata_sg5=subset(modeldata,!is.na(etasante_g) & DEPAMB>0 & !is.na(age_classe)
                     & !is.na(homme) & !is.na(etude_c) & !is.na(CMU_x)
                     & !is.na(CC_x) & !is.na(CSP_cat) & !is.na(fum_cat) & !is.na(verre) &
                       !is.na(difpayer_c) & !is.na(COUPLE_c) & !is.na(RISQUE_classe) &  !is.na(AVENIR_classe) & !is.na(age_classe) & !is.na(adl_limit) &  !is.na(TPS) &
                       !is.na(PBPATHOL_classe) & !is.na(etatsante_score))

#Log des depenses
modeldata_sg5=modeldata_sg5 %>%
  mutate(LOGDEP=log(DEPAMB)) %>% 
  filter(etasante_g!="0") %>% 
  droplevels()
```

```{r}
###Caracteristiques totale###
#Annotation#
annot=data.frame(label=c("Age","Gender","Socioprofessional category","Complementary healthcare insurance","Universal healthcare insurance","Financial difficulties","Income","Married","Drinking","Smoking","Risk seeking","Education","Time-preference","Experience of seclusion","Size of urban area","Social life","Self-perceived health","Number of ADL","Number of pathologies","Frailty"),
variable=c("age_classe","homme","CSP_cat","CC_x","CMU_x","difpayer_c","revenu_dummy","COUPLE_c","verre","fum_cat","RISQUE_classe","etude_c","AVENIR_classe","ISOLEMENT_c","pole","social","etasante_g","adl_limit","PBPATHOL_classe","fragilite_cat"))

##Statistiques pour les variables discretes
stat_desc=modeldata_sg5 %>% 
  select(age_classe,homme,CSP_cat,CC_x,CMU_x,difpayer_c,revenu_dummy,COUPLE_c,verre,fum_cat,RISQUE_classe,etude_c,AVENIR_classe,ISOLEMENT_c,pole,social,etasante_g,adl_limit,PBPATHOL_classe,fragilite_cat) %>%
  gather(variable, value,age_classe,homme,CSP_cat,CC_x,CMU_x,difpayer_c,revenu_dummy,COUPLE_c,verre,fum_cat,RISQUE_classe,etude_c,AVENIR_classe,ISOLEMENT_c,pole,social,etasante_g,adl_limit,PBPATHOL_classe,fragilite_cat) %>%
  group_by(variable, value) %>%
  summarise (n = n()) %>%
  mutate(freq = paste0(round(n / sum(n)*100,digits=1),"%")) %>% 
           full_join(.,annot,by=c("variable")) %>% 
  replace_na(.,list(n="0",freq="0%")) %>% 
  filter(value!="Non")%>% 
  ungroup() %>% 
  select(-variable)%>%
  select(label,value,n,freq) %>% 
  setNames(.,c("Variable","Category","N","%"))%>% 
  select(Variable,Category,N,`%`)
stat_desc[which(stat_desc$Category=="Oui"),"Category"]=""
stat_desc[which(stat_desc$Category=="" & stat_desc$Variable=="Financial difficulties"),"Category"]="Oui"

#Rajout du total#
dummy=stat_desc[1,]
dummy$Category=""
dummy$N=as.character(dim(modeldata_sg5)[1])
dummy$`%`=""
dummy$Variable="Total"

stat_desc=bind_rows(dummy,stat_desc)

###Caracteristiques renoncement###
#Test du chi deux#

chis_fun=function(var){
  round(chisq.test(table(modeldata_sg5$renonc_flg_all,
                   eval(parse(text=paste0("modeldata_sg5$",var)))))$p.value,digits=3)
}

list_var=c("age_classe","homme","CSP_cat","CC_x","CMU_x","difpayer_c","revenu_dummy","COUPLE_c","verre","fum_cat","RISQUE_classe","etude_c","AVENIR_classe","ISOLEMENT_c","pole","social","etasante_g","adl_limit","PBPATHOL_classe","fragilite_cat")

chis_summary=list_var %>% 
  map(chis_fun) %>% 
  unlist() %>% 
  as.character() %>% 
  ifelse(.=="0","<0.001",.) %>% 
  cbind(pvalue=.,variable=list_var) %>% 
  tbl_df()

stat_group=function(renonc){
stat_desc=modeldata_sg5 %>% 
  filter(renonc_flg_all==renonc) %>% 
  select(age_classe,homme,CSP_cat,CC_x,CMU_x,difpayer_c,revenu_dummy,COUPLE_c,verre,fum_cat,RISQUE_classe,etude_c,AVENIR_classe,ISOLEMENT_c,pole,social,etasante_g,adl_limit,PBPATHOL_classe,fragilite_cat) %>%
  gather(variable, value,age_classe,homme,CSP_cat,CC_x,CMU_x,difpayer_c,revenu_dummy,COUPLE_c,verre,fum_cat,RISQUE_classe,etude_c,AVENIR_classe,ISOLEMENT_c,pole,social,etasante_g,adl_limit,PBPATHOL_classe,fragilite_cat) %>%
  group_by(variable, value) %>%
  summarise (n = n()) %>%
  mutate(freq = paste0(round(n / sum(n)*100,digits=1),"%")) %>% 
           full_join(.,annot,by=c("variable")) %>% 
  full_join(.,chis_summary,by=c("variable")) %>% 
  replace_na(.,list(n="0",freq="0%")) %>% 
  filter(value!="Non")%>%
  ungroup() %>% 
  select(-variable) %>% 
  setNames(.,c("Category","N","%","Variable","P-value")) %>% 
  select(Variable,Category,N,`%`,`P-value`)
stat_desc[which(stat_desc$Category=="Oui"),"Category"]=""
stat_desc[which(stat_desc$Category=="" & stat_desc$Variable=="Financial difficulties"),"Category"]="Oui"

dummy=stat_desc[1,]
dummy$Category=""
dummy$N=as.character(modeldata_sg5 %>% filter(renonc_flg_all==renonc) %>% nrow(.))
dummy$`%`=""
dummy$Variable="Total"

stat_desc=bind_rows(dummy,stat_desc)

return(stat_desc)
}

stat_renonc_oui=stat_group(renonc="Oui")
stat_renonc_oui=stat_renonc_oui %>% 
  rename(.,N_Yes=N,`%_Yes`=`%`) %>% 
  select(-`P-value`)

stat_renonc_non=stat_group(renonc="Non")
stat_renonc_non=stat_renonc_non %>% 
  rename(.,N_No=N,`%_No`=`%`)

stat_renonc=stat_renonc_oui %>% 
  full_join(.,stat_renonc_non,by=c("Variable","Category")) %>% 
  mutate(`P-value`=ifelse(Variable=="Total","",`P-value`))

```

```{r}
###Moyenne des depenses en ambulatoire####
#Statistiques descriptives pour les variables continues
temp=modeldata_sg5%>% 
  select(DEPAMB) %>% 
  summarise_all(funs(Mean=mean(.,na.rm=TRUE),SD=sd(.,na.rm=TRUE),
                     P25=quantile(.,probs=c(0.25),na.rm=TRUE),Median=median(.,na.rm=TRUE),
            P75=quantile(.,probs=c(0.75),na.rm=TRUE))) %>% 
  mutate_each(funs(round(.,digits=0))) %>% 
  mutate(IQR=paste0(P25,"-",P75)) %>% 
  select(Mean,SD,Median,IQR)

#Test de wilcoxon#
dep_wilcox=wilcox.test(subset(modeldata_sg5,modeldata_sg5$renonc_flg_all=="Oui")$DEPAMB,
                       subset(modeldata_sg5,modeldata_sg5$renonc_flg_all=="Non")$DEPAMB)$p.value

temp_2=modeldata_sg5%>% 
  group_by(renonc_flg_all) %>% 
  select(DEPAMB) %>% 
  summarise_all(funs(moyenne=mean(.,na.rm=TRUE),std=sd(.,na.rm=TRUE),P25=round(quantile(.,probs=c(0.25),na.rm=TRUE),digits=0),mediane=median(.,na.rm=TRUE),
            P75=round(quantile(.,probs=c(0.75),na.rm=TRUE),digits=0))) %>% 
  gather(key,value,-renonc_flg_all) %>% 
  unite("stat_n",c("key","renonc_flg_all")) %>% 
  spread(stat_n,value) %>% 
  mutate_each(funs(round(.,digits=0))) %>% 
mutate(IQR_Oui=paste0(P25_Oui,"-",P75_Oui)) %>% 
  mutate(IQR_Non=paste0(P25_Non,"-",P75_Non)) %>% 
  select(moyenne_Oui,std_Oui,mediane_Oui,IQR_Oui,moyenne_Non,std_Non,mediane_Non,IQR_Non)%>% 
  mutate(`P-valeur`=round(dep_wilcox,digits=3))

dep_sum=temp %>%
  bind_cols(.,temp_2)

```


```{r,fig.height=3,fig.width=2}
#Graphe renoncement total#
renonc_stat=modeldata_sg5 %>% 
  mutate(renonc_flg_all=forcats::fct_recode(renonc_flg_all,
                                            "Yes"="Oui",
                                            "No"="Non")) %>% 
           mutate(renonc_flg_all=relevel(renonc_flg_all,ref="No")) %>% 
  group_by(renonc_flg_all) %>% 
  tally %>%
  mutate(freq=round(n/sum(n)*100,digits=1)) %>% 
  ungroup

gg1=ggplot(data=renonc_stat,aes(x=renonc_flg_all,y=freq))+
  geom_bar(stat="identity",fill="steelblue")+
  xlab(label="Unmet needs")+
  ylab(label="%")+
  geom_text(aes(label=freq), vjust=1.6, color="white", size=3.5)+
  labs(colour="Age")+
  theme_gdocs()
```

```{r}
#Renoncement par tranche d'age#
renonc_stat=modeldata_sg5 %>%
    mutate(renonc_flg_all=forcats::fct_recode(renonc_flg_all,
                                            "Yes"="Oui",
                                            "No"="Non")) %>% 
           mutate(renonc_flg_all=relevel(renonc_flg_all,ref="No")) %>% 
  group_by(renonc_flg_all,age_classe) %>% 
  tally() %>% 
  ungroup() %>% 
  group_by(age_classe) %>% 
  mutate(freq=round(n/sum(n)*100,digits=1))

gg2=ggplot(data=renonc_stat,aes(x=renonc_flg_all,y=freq,group=age_classe,fill=age_classe))+
  geom_bar(stat="identity",position="dodge")+
  xlab(label="Unmet needs")+
  ylab(label="%")+
  geom_text(aes(label=freq),position=position_dodge(0.9),vjust=1.6, color="white", size=3.5)+
  guides(fill=guide_legend(title="Age"))+
  theme_gdocs()
```

```{r,fig.height=7,fig.width=5}
#Depenses par tranche d'age#

gg3=ggplot(modeldata_sg5, aes(x=LOGDEP))+
  geom_histogram(aes(y=..density..),color="black",fill="#0d488a")+
  geom_density(alpha=0.6,color="#e86800")+
    facet_grid(age_classe~.)+
  xlab("Ambulatory healthcare expenditures (log)")+
  ylab("Density")+
    theme_gdocs()
```


```{r,fig.height=7,fig.width=5}
#Depenses par niveau de fragilite#

gg4=ggplot(modeldata_sg5, aes(x=LOGDEP))+
  geom_histogram(aes(y=..density..),color="black",fill="#0d488a")+
  geom_density(alpha=0.6,color="#e86800")+
    facet_grid(fragilite_cat~.)+
  xlab("Ambulatory healthcare expenditures (log)")+
  ylab("Density")+
    theme_gdocs()
```


```{r,fig.height=5,fig.width=7}
#Renoncement par tranche d'age#
mean_stat=modeldata_sg5 %>% 
  group_by(age_classe,fragilite_cat) %>% 
  summarise(mean_dep=mean(DEPAMB))%>% 
  ungroup()

gg5=ggplot(data=mean_stat,aes(x=age_classe,y=mean_dep,group=fragilite_cat,fill=fragilite_cat))+
  geom_bar(stat="identity",position="dodge")+
  xlab(label="Age")+
  ylab(label="Mean of ambulatory healthcare expenditures (in euros)")+
  guides(fill=guide_legend(title="Frailty"))+
  scale_y_continuous(breaks=seq(0,6000,1000))+
  theme_gdocs()
```

```{r}
#Renoncement par tranche d'age#
mean_stat=modeldata_sg5 %>%
    mutate(renonc_flg_all=forcats::fct_recode(renonc_flg_all,
                                            "Yes"="Oui",
                                            "No"="Non")) %>% 
           mutate(renonc_flg_all=relevel(renonc_flg_all,ref="No")) %>% 
  group_by(renonc_flg_all,fragilite_cat) %>% 
  summarise(mean_dep=mean(DEPAMB))%>% 
  ungroup()

gg6=ggplot(data=mean_stat,aes(x=renonc_flg_all,y=mean_dep,group=fragilite_cat,fill=fragilite_cat))+
  geom_bar(stat="identity",position="dodge")+
  xlab(label="Unmet needs")+
  ylab(label="Mean of ambulatory healthcare expenditures (in euros)")+
  guides(fill=guide_legend(title="Frailty"))+
  scale_y_continuous(breaks=seq(0,6000,1000))+
  theme_gdocs()
```

```{r}
#Depenses par poste#
mean_stat=modeldata_sg5 %>% 
  summarise_at(vars(DEPOMN,DEPSPE,DEPDEN,DEPSAG,DEPINF,DEPKIN,DEPAAU,DEPBIO,DEPURG,DEPPHA,DEPMAT,DEPOPT,DEPTRA,DEPPRO,DEPSOIN_E),funs(mean)) %>% 
  gather(key,value) %>% 
  arrange(value)
mean_stat=mean_stat %>% 
  mutate(key=case_when(
    key=="DEPOMN" ~ "GPs",
    key=="DEPSPE" ~ "Specialists",
    key=="DEPDEN" ~ "Dentists",
    key=="DEPSAG" ~ "Sages-femme",
    key=="DEPINF" ~ "Nurses",
    key=="DEPKIN" ~ "Physiotherapists",
    key=="DEPAAU" ~ "Other auxiliaries",
    key=="DEPBIO" ~ "Biomedical analyses",
    key=="DEPURG" ~ "Emergency",
    key=="DEPPHA" ~ "Medicine",
    key=="DEPMAT" ~ "Health materials",
    key=="DEPOPT" ~ "Optics",
    key=="DEPTRA" ~ "Transport",
    key=="DEPPRO" ~ "Prosthetics",
    key=="DEPSOIN_E" ~ "Etranger"
  )) %>% 
  mutate(value=round(value,digits=0)) %>% 
  filter(!(key %in% c("Etranger","Sages-femme")))
  

gg7=ggplot(data=mean_stat,aes(x=reorder(key, -value),y=value,fill=key))+
  geom_bar(stat="identity")+
  ylab(label="Mean of healthcare expenditures (in euros)")+
  xlab(label="")+
  geom_text(aes(label=value), color="black", size=2.5)+
  guides(fill=FALSE)+
  scale_x_discrete()+
  theme_gdocs()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
#Depenses par poste par tranche d'age#
mean_stat=modeldata_sg5 %>% 
  group_by(age_classe) %>% 
  summarise_at(vars(DEPOMN,DEPSPE,DEPDEN,DEPSAG,DEPINF,DEPKIN,DEPAAU,DEPBIO,DEPURG,DEPPHA,DEPMAT,DEPOPT,DEPTRA,DEPPRO,DEPSOIN_E),funs(mean)) %>% 
  gather(key,value,-age_classe) %>% 
  arrange(value)
mean_stat=mean_stat %>% 
  mutate(key=case_when(
    key=="DEPOMN" ~ "GPs",
    key=="DEPSPE" ~ "Specialists",
    key=="DEPDEN" ~ "Dentists",
    key=="DEPSAG" ~ "Sages-femme",
    key=="DEPINF" ~ "Nurses",
    key=="DEPKIN" ~ "Physiotherapists",
    key=="DEPAAU" ~ "Other auxiliaries",
    key=="DEPBIO" ~ "Biomedical analyses",
    key=="DEPURG" ~ "Emergency",
    key=="DEPPHA" ~ "Medicine",
    key=="DEPMAT" ~ "Health materials",
    key=="DEPOPT" ~ "Optics",
    key=="DEPTRA" ~ "Transport",
    key=="DEPPRO" ~ "Prosthetics",
    key=="DEPSOIN_E" ~ "Etranger"
  )) %>% 
  mutate(value=round(value,digits=0)) %>% 
  filter(!(key %in% c("Etranger","Sages-femme")))
  

gg8=ggplot(data=mean_stat,aes(x=reorder(key, -value),y=value,fill=key))+
  geom_bar(stat="identity")+
  ylab(label="Mean of healthcare expenditures (in euros)")+
  xlab(label="")+
  geom_text(aes(label=value), color="black", size=2.5)+
  guides(fill=FALSE)+
  scale_x_discrete()+
  theme_gdocs()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  facet_grid(age_classe~.)
```

```{r}
#Graphe visite recommandee#
recomm_stat=modeldata_sg5 %>%
    mutate(VISIT_RECOM=forcats::fct_recode(VISIT_RECOM,
                                            "Yes"="Oui",
                                            "No"="Non")) %>% 
           mutate(VISIT_RECOM=relevel(VISIT_RECOM,ref="No")) %>% 
  group_by(VISIT_RECOM) %>% 
  tally %>%
  mutate(freq=round(n/sum(n)*100,digits=1)) %>% 
  ungroup

gg9=ggplot(data=recomm_stat,aes(x=VISIT_RECOM,y=freq))+
  geom_bar(stat="identity",fill="steelblue")+
  xlab(label="At least one recommanded visit")+
  ylab(label="%")+
  geom_text(aes(label=freq), color="black", size=3.5)+
  theme_gdocs()

#Graphe visite recommandee#
recomm_stat=modeldata_sg5 %>% 
      mutate(VISIT_RECOM=forcats::fct_recode(VISIT_RECOM,
                                            "Yes"="Oui",
                                            "No"="Non")) %>% 
           mutate(VISIT_RECOM=relevel(VISIT_RECOM,ref="No")) %>% 
  group_by(VISIT_RECOM) %>% 
  tally %>%
  mutate(freq=round(n/sum(n)*100,digits=1)) %>% 
  ungroup

gg9=ggplot(data=recomm_stat,aes(x=VISIT_RECOM,y=freq))+
  geom_bar(stat="identity",fill="steelblue")+
  xlab(label="At least one recommanded visit")+
  ylab(label="%")+
  geom_text(aes(label=freq), color="black", size=3.5)+
  theme_gdocs()


#Graphe visite recommandee par tranche d'age#
recomm_stat=modeldata_sg5 %>%
      mutate(VISIT_RECOM=forcats::fct_recode(VISIT_RECOM,
                                            "Yes"="Oui",
                                            "No"="Non")) %>% 
           mutate(VISIT_RECOM=relevel(VISIT_RECOM,ref="No")) %>% 
  group_by(VISIT_RECOM,age_classe) %>% 
  tally() %>% 
  ungroup() %>% 
  group_by(age_classe) %>% 
  mutate(freq=round(n/sum(n)*100,digits=1))

gg10=ggplot(data=recomm_stat,aes(x=VISIT_RECOM,y=freq,group=age_classe,fill=age_classe))+
  geom_bar(stat="identity",position="dodge")+
  xlab(label="At least one recommanded visit")+
  ylab(label="%")+
  geom_text(aes(label=freq),position=position_dodge(0.9), color="black", size=3.5)+
  guides(fill=guide_legend(title="Age"))+
  theme_gdocs()
```

```{r}
#Graphe - Nombre de visites generaliste et specialiste#
gg11=ggplot(modeldata_sg5, aes(x=SEAC_OMN))+
  geom_histogram(aes(y=..density..),color="black",fill="#0d488a",binwidth = 2)+
  geom_density(alpha=0.6,color="#e86800")+
  xlab("Number of GP visits")+
  ylab("Density")+
    scale_x_continuous(breaks=seq(0,30,5))+
    theme_gdocs()

gg12=ggplot(modeldata_sg5, aes(x=SEAC_SPE))+
  geom_histogram(aes(y=..density..),color="black",fill="#0d488a",binwidth = 2)+
  geom_density(alpha=0.6,color="#e86800")+
  xlab("Number of specialist visits")+
  ylab("Density")+
  scale_x_continuous(breaks=seq(0,30,5),limits = c(0, 30))+
    theme_gdocs()


```

```{r}
#Graphe - Nombre de visites generaliste et specialiste par age#
gg13=ggplot(modeldata_sg5, aes(x=SEAC_OMN))+
  geom_histogram(aes(y=..density..),color="black",fill="#0d488a",binwidth = 2)+
  geom_density(alpha=0.6,color="#e86800")+
      facet_grid(age_classe~.)+
  xlab("Number of GP visits")+
  ylab("Density")+
    scale_x_continuous(breaks=seq(0,30,5))+
    theme_gdocs()

gg14=ggplot(modeldata_sg5, aes(x=SEAC_SPE))+
  geom_histogram(aes(y=..density..),color="black",fill="#0d488a",binwidth = 2)+
  geom_density(alpha=0.6,color="#e86800")+
      facet_grid(age_classe~.)+
  xlab("Number of specialist visits")+
  ylab("Density")+
    scale_x_continuous(breaks=seq(0,30,5),limits = c(0, 30))+
    theme_gdocs()
```

```{r}
#Graphe - Nombre de visites generaliste et specialiste par fragilite#
gg15=ggplot(modeldata_sg5, aes(x=SEAC_OMN))+
  geom_histogram(aes(y=..density..),color="black",fill="#0d488a",binwidth = 2)+
  geom_density(alpha=0.6,color="#e86800")+
      facet_grid(fragilite_cat~.)+
  xlab("Number of GP visits")+
  ylab("Density")+
    scale_x_continuous(breaks=seq(0,30,5))+
    theme_gdocs()

gg16=ggplot(modeldata_sg5, aes(x=SEAC_SPE))+
  geom_histogram(aes(y=..density..),color="black",fill="#0d488a",binwidth = 2)+
  geom_density(alpha=0.6,color="#e86800")+
      facet_grid(fragilite_cat~.)+
  xlab("Number of specialist visits")+
  ylab("Density")+
    scale_x_continuous(breaks=seq(0,30,5),limits = c(0, 30))+
    theme_gdocs()
```

```{r}
#Depenses en fonction du renoncement#
temp=modeldata_sg5 %>% 
    mutate(renonc_flg_all=forcats::fct_recode(renonc_flg_all,
                                            "Yes"="Oui",
                                            "No"="Non")) %>% 
           mutate(renonc_flg_all=relevel(renonc_flg_all,ref="No"))

gg17=ggplot(temp, aes(x=LOGDEP))+
  geom_histogram(aes(y=..density..),color="black",fill="#0d488a")+
  geom_density(alpha=0.6,color="#e86800")+
    facet_grid(renonc_flg_all~.)+
  xlab("Ambulatory healthcare expenditures (log)")+
  ylab("Density")+
    theme_gdocs()
```

```{r}
#Depenses par poste en fonction du renoncement#
mean_stat=modeldata_sg5 %>%
      mutate(renonc_flg_all=forcats::fct_recode(renonc_flg_all,
                                            "Yes"="Oui",
                                            "No"="Non")) %>% 
           mutate(renonc_flg_all=relevel(renonc_flg_all,ref="No")) %>% 
  group_by(renonc_flg_all) %>% 
  summarise_at(vars(DEPOMN,DEPSPE,DEPDEN,DEPSAG,DEPINF,DEPKIN,DEPAAU,DEPBIO,DEPURG,DEPPHA,DEPMAT,DEPOPT,DEPTRA,DEPPRO,DEPSOIN_E),funs(mean)) %>% 
  gather(key,value,-renonc_flg_all) %>% 
  arrange(value)
mean_stat=mean_stat %>% 
  mutate(key=case_when(
    key=="DEPOMN" ~ "GPs",
    key=="DEPSPE" ~ "Specialists",
    key=="DEPDEN" ~ "Dentists",
    key=="DEPSAG" ~ "Sages-femme",
    key=="DEPINF" ~ "Nurses",
    key=="DEPKIN" ~ "Physiotherapists",
    key=="DEPAAU" ~ "Other auxiliaries",
    key=="DEPBIO" ~ "Biomedical analyses",
    key=="DEPURG" ~ "Emergency",
    key=="DEPPHA" ~ "Medicine",
    key=="DEPMAT" ~ "Health materials",
    key=="DEPOPT" ~ "Optics",
    key=="DEPTRA" ~ "Transport",
    key=="DEPPRO" ~ "Prosthetics",
    key=="DEPSOIN_E" ~ "Etranger"
  )) %>% 
  mutate(value=round(value,digits=0)) %>% 
  filter(!(key %in% c("Etranger","Sages-femme")))
  

gg18=ggplot(data=mean_stat,aes(x=reorder(key, -value),y=value,fill=key))+
  geom_bar(stat="identity")+
  ylab(label="Mean of healthcare expenditures (in euros)")+
  xlab(label="")+
  geom_text(aes(label=value), color="black", size=2.5)+
  guides(fill=FALSE)+
  scale_x_discrete()+
  theme_gdocs()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  facet_grid(renonc_flg_all~.)
```

```{r}
#Test de wilcoxon sur les depenses#
wilc_dep=function(var){
a=modeldata_sg5 %>% 
    filter(renonc_flg_all=="Oui") %>% 
    pull(!!var)
b=modeldata_sg5 %>% 
    filter(renonc_flg_all=="Non") %>% 
    pull(!!var)
wil_p=wilcox.test(a,b) %>%
  .$p.value
}

#List des variables depenses#
list_dep=modeldata_sg5 %>% 
  select(starts_with("DEP")) %>% 
  names(.)
list_dep=list_dep[c(-1,-2,-19,-20)]

temp=modeldata_sg5%>% 
  select(list_dep) %>%
  select(-DEPSOIN_E,-DEPSAG) %>% 
  summarise_all(funs(Mean=mean(.,na.rm=TRUE),SD=sd(.,na.rm=TRUE),P25=quantile(.,probs=c(0.25),na.rm=TRUE),Median=median(.,na.rm=TRUE),
            P75=quantile(.,probs=c(0.75),na.rm=TRUE))) %>% 
  mutate_each(funs(round(.,digits=0))) %>%
  gather(key,value) %>% 
  separate(.,"key",c("Variable","stat")) %>% 
  spread(stat,value) %>% 
  mutate(IQR=paste0(P25,"-",P75)) %>% 
  select(Variable,Mean,SD,Median,IQR)

temp_2=modeldata_sg5%>% 
  group_by(renonc_flg_all) %>% 
  select(list_dep) %>% 
  select(-DEPSOIN_E,-DEPSAG) %>%
  summarise_all(funs(Mean=round(mean(.,na.rm=TRUE),digits=0),SD=round(sd(.,na.rm=TRUE),digits=0),P25=round(quantile(.,probs=c(0.25),na.rm=TRUE),digits=0),Median=round(median(.,na.rm=TRUE),digits=0),
            P75=round(quantile(.,probs=c(0.75),na.rm=TRUE),digits=0))) %>% 
  gather(key,value,-renonc_flg_all) %>% 
  separate(.,"key",c("Variable","stat"))%>% 
  unite("stat_n",c("stat","renonc_flg_all")) %>% 
  spread(stat_n,value) %>% 
mutate(IQR_Oui=paste0(P25_Oui,"-",P75_Oui)) %>% 
  mutate(IQR_Non=paste0(P25_Non,"-",P75_Non)) %>% 
  select(Variable,Mean_Oui,SD_Oui,Median_Oui,IQR_Oui,Mean_Non,SD_Non,Median_Non,IQR_Non)

#Test de wilcoxon#
wilc_pval=list_dep %>% 
  map(wilc_dep) %>% 
  unlist %>% 
  tbl_df() %>% 
  mutate(Variable=list_dep)

#Jointure avec les donnees#
temp_2=temp_2 %>% 
  left_join(.,wilc_pval,by=c("Variable")) %>% 
  rename(.,"P-value"="value") %>% 
  mutate(`P-value`=round(`P-value`,digits=3))

dep_sum_all=temp %>%
  left_join(.,temp_2,by=c("Variable")) %>% 
  mutate(numb=ifelse(Variable=="DEPAMB",2,1)) %>% 
  arrange(-numb) %>% 
  select(-numb) %>% 
  mutate(Variable=case_when(
    Variable=="DEPAMB"~ "Total",
    Variable=="DEPOMN" ~ "GPs",
    Variable=="DEPSPE" ~ "Specialists",
    Variable=="DEPDEN" ~ "Dentists",
    Variable=="DEPSAG" ~ "Sages-femme",
    Variable=="DEPINF" ~ "Nurses",
    Variable=="DEPKIN" ~ "Physiotherapists",
    Variable=="DEPAAU" ~ "Other auxiliaries",
    Variable=="DEPBIO" ~ "Biomedical analyses",
    Variable=="DEPURG" ~ "Emergency",
    Variable=="DEPPHA" ~ "Medicine",
    Variable=="DEPMAT" ~ "Health materials",
    Variable=="DEPOPT" ~ "Optics",
    Variable=="DEPTRA" ~ "Transport",
    Variable=="DEPPRO" ~ "Prosthetics",
    Variable=="DEPSOIN_E" ~ "Etranger"
  )) %>% 
  filter(Variable!="Sages-femme" & Variable!="Etranger") %>% 
  arrange(desc(Median))
```


```{r}
#Creation du fichier word avec les graphes#
library(officer)
library(devEMF)

# produce an emf file containing the ggplot
filename_1=tempfile(fileext = ".emf")
emf(file = filename_1, width = 6, height = 5)
print(gg1)
dev.off()

filename_2=tempfile(fileext = ".emf")
emf(file = filename_2, width = 6, height = 5)
print(gg2)
dev.off()

filename_3=tempfile(fileext = ".emf")
emf(file = filename_3, width = 6, height = 7)
print(gg3)
dev.off()

filename_4=tempfile(fileext = ".emf")
emf(file = filename_4, width = 6, height = 7)
print(gg4)
dev.off()

filename_5=tempfile(fileext = ".emf")
emf(file = filename_5, width = 6, height = 5)
print(gg5)
dev.off()

filename_6=tempfile(fileext = ".emf")
emf(file = filename_6, width = 6, height = 5)
print(gg6)
dev.off()

filename_7=tempfile(fileext = ".emf")
emf(file = filename_7, width = 6, height = 5)
print(gg7)
dev.off()

filename_8=tempfile(fileext = ".emf")
emf(file = filename_8, width = 6, height = 7)
print(gg8)
dev.off()

filename_9=tempfile(fileext = ".emf")
emf(file = filename_9, width = 6, height = 5)
print(gg9)
dev.off()

filename_10=tempfile(fileext = ".emf")
emf(file = filename_10, width = 6, height = 5)
print(gg10)
dev.off()

filename_11=tempfile(fileext = ".emf")
emf(file = filename_11, width = 6, height = 5)
print(gg11)
dev.off()

filename_12=tempfile(fileext = ".emf")
emf(file = filename_12, width = 6, height = 5)
print(gg12)
dev.off()

filename_13=tempfile(fileext = ".emf")
emf(file = filename_13, width = 6, height = 7)
print(gg13)
dev.off()

filename_14=tempfile(fileext = ".emf")
emf(file = filename_14, width = 6, height = 7)
print(gg14)
dev.off()

filename_15=tempfile(fileext = ".emf")
emf(file = filename_15, width = 6, height = 7)
print(gg15)
dev.off()

filename_16=tempfile(fileext = ".emf")
emf(file = filename_16, width = 6, height = 7)
print(gg16)
dev.off()

filename_17=tempfile(fileext = ".emf")
emf(file = filename_17, width = 6, height = 7)
print(gg17)
dev.off()

filename_18=tempfile(fileext = ".emf")
emf(file = filename_18, width = 6, height = 7)
print(gg18)
dev.off()

read_docx() %>% 
  body_add_par(value = "Graphiques", style = "heading 1") %>% 
  body_add_img(src = filename_1, width = 6, height = 5) %>% 
  body_add_img(src = filename_2, width = 6, height = 5) %>% 
  body_add_img(src = filename_3, width = 6, height = 7) %>% 
  body_add_img(src = filename_4, width = 6, height = 7) %>% 
  body_add_img(src = filename_17, width = 6, height = 7) %>% 
  body_add_img(src = filename_5, width = 6, height = 5) %>% 
  body_add_img(src = filename_6, width = 6, height = 5) %>% 
  body_add_img(src = filename_7, width = 6, height = 5) %>% 
  body_add_img(src = filename_8, width = 6, height = 7) %>% 
  body_add_img(src = filename_18, width = 6, height = 7) %>% 
  body_add_img(src = filename_9, width = 6, height = 5) %>% 
  body_add_img(src = filename_10, width = 6, height = 5) %>% 
  body_add_img(src = filename_11, width = 6, height = 5) %>% 
  body_add_img(src = filename_12, width = 6, height = 5) %>% 
  body_add_img(src = filename_13, width = 6, height = 7) %>% 
  body_add_img(src = filename_14, width = 6, height = 7) %>% 
  body_add_img(src = filename_15, width = 6, height = 7) %>% 
  body_add_img(src = filename_16, width = 6, height = 7) %>% 
  body_add_par(value = "Tables", style = "heading 1") %>% 
  body_add_par(value = "Total", style = "heading 2") %>% 
  body_add_table(value = stat_desc, style = "table_template" ) %>% 
  body_add_par(value = "Chez ceux qui renoncent et ceux qui ne renoncent pas", style = "heading 2")%>%
  body_add_table(value = stat_renonc, style = "table_template" ) %>%
  body_end_section_continuous() %>% 
  body_add_par(value = "Dépenses en fonction du renoncement", style = "heading 2") %>% 
  body_add_table(value = dep_sum, style = "table_template" ) %>% 
      body_end_section_landscape() %>% 
    body_add_par(value = "Dépenses par poste en fonction du renoncement", style = "heading 2") %>% 
  body_add_table(value = dep_sum_all, style = "table_template" ) %>% 
      body_end_section_landscape() %>% 
  print(target = "Statistiques_descriptives_eng.docx")
```
