---
title: "SEM model for unmet needs and health care expenditures"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
###Libraries###
library(haven)
library(tidyverse)
library(readxl)
library(forcats)
library(qgraph)
library(Hmisc)
```

```{r}
###Data import###
elders=haven::read_sas("/Users/thomaslaurent/Documents/Cours-M2/Memoire/Project/file_180505/elders_180505.sas7bdat",catalog_file="//Users/thomaslaurent/Documents/Cours-M2/Memoire/Project/file_180505/formats.sas7bcat",encoding="latin1")

##Conversion en factor
#Lecture du fichier d'annotation
annot=read_excel("/Users/thomaslaurent/Documents/Cours-M2/Memoire/Project/file_180505/Variable_Dataset_cleaned.xlsx")
```

```{r}
###Conversion en factor et definition des niveaux de reference###

modeldata=elders %>% 
  mutate(age_classe=droplevels(as_factor(age_classe))) %>% 
  mutate(etude_c=droplevels(as_factor(etude_c))) %>% 
  mutate(revucinsee_c=droplevels(as_factor(revucinsee_c))) %>% 
  mutate(CC=droplevels(as_factor(CC)))%>% 
  mutate(risque_c=droplevels(as_factor(risque_c))) %>% 
  mutate(alcool_c=droplevels(haven::as_factor(alcool_c))) %>% 
  mutate(COUPLE_c=droplevels(as_factor(COUPLE_c))) %>% 
  mutate(difpayer_c=droplevels(as_factor(difpayer_c))) %>% 
  mutate(fum_cat=droplevels(as_factor(fum_cat))) %>% 
  mutate(TPS_c=droplevels(as_factor(TPS_c))) %>% 
  mutate(etasante_g=droplevels(as_factor(etasante_g))) %>% 
  mutate(RENONC_FLG=droplevels(as_factor(RENONC_FLG))) %>% 
  mutate(homme=droplevels(as_factor(homme))) %>% 
  mutate(etasante_g=forcats::fct_recode(etasante_g,
                               "Mauvais/Moyen"="Tres mauvais",
                               "Mauvais/Moyen"="Mauvais",
                               "Mauvais/Moyen"="Assez Bon",
                               "Bon/Tres bon"="Bon",
                               "Bon/Tres bon"="Tres bon")) %>%
  mutate(age_classe2=forcats::fct_recode(age_classe,
                               "80-"="65-69",
                               "80-"="70-74",
                               "80-"="75-79",
                               "80+"="80-84",
                               "80+"="85-89",
                               "80+"="90+")) %>%
  mutate(age_classe=forcats::fct_recode(age_classe,
                               "65-69"="65-69",
                               "70-74"="70-74",
                               "75-79"="75-79",
                               "80-84"="80-84",
                               "85+"="85-89",
                               "85+"="90+")) %>%
  mutate(etasante_g=relevel(etasante_g,ref="Bon/Tres bon")) %>% 
  mutate(RENONC_FLG=relevel(RENONC_FLG,ref="Non")) %>% 
  mutate(difpayer_c=relevel(difpayer_c,ref="Non")) %>% 
    mutate(COUPLE_c=relevel(COUPLE_c,ref="Non")) %>% 
  mutate(renonc_gen=droplevels(as_factor(renonc_gen))) %>% 
  mutate(renonc_gen=relevel(renonc_gen,ref="Non")) %>% 
  mutate(renonc_gp=droplevels(as_factor(renonc_gp))) %>% 
  mutate(renonc_gp=relevel(renonc_gp,ref="Non")) %>% 
  mutate(renonc_spe=droplevels(as_factor(renonc_spe))) %>% 
  mutate(renonc_spe=relevel(renonc_spe,ref="Non")) %>% 
  mutate(risque_c=relevel(risque_c,ref="Prise de risque")) %>% 
  mutate(fragilite_code=factor(ifelse(fragilite>=3,1,0))) %>% 
  mutate(etatsante_factor=factor(etasante_x)) %>% 
  mutate(fum_cat=relevel(fum_cat,ref="Ne fume pas")) %>% 
  mutate(CMU_x=droplevels(as_factor(CMU_x))) %>% 
  mutate(CMU_x=relevel(CMU_x,ref="Non")) %>% 
  mutate(CC_x=droplevels(as_factor(CC_x))) %>% 
  mutate(CC_x=relevel(CC_x,ref="Non")) %>% 
  mutate(CSP_cat=droplevels(as_factor(CSP_cat))) %>% 
  mutate(ISOLEMENT_c=droplevels(as_factor(ISOLEMENT_c))) %>% 
  mutate(ISOLEMENT_c=relevel(ISOLEMENT_c,ref="Non")) %>% 
  mutate(renonc_flg_all=droplevels(as_factor(renonc_flg_all))) %>% 
  mutate(renonc_flg_all=relevel(renonc_flg_all,ref="Non")) %>% 
  mutate(fragilite_cat=droplevels(as_factor(fragilite))) %>% 
  mutate(fragilite_cat=forcats::fct_recode(fragilite_cat,
                                           "Robuste"="0",
                                           "Pre-fragilite"="1",
                                           "Pre-fragilite"="2",
                                           "Fragilite"="3",
                                           "Fragilite"="4",
                                           "Fragilite"="5")) %>% 
  mutate(alcool_num=as.numeric(alcool_c)) %>% 
  mutate(alcool_cat=factor(alcool_num,
                              labels=c("Jamais","1 fois par mois ou moins",
                                       "2 a 4 fois par mois"))) %>% 
  mutate(TPSAMI_x=droplevels(as_factor(TPSAMI_c))) %>% 
  mutate(TPSASSO_x=droplevels(as_factor(TPSASSO_c))) %>% 
  mutate(TPSFAMIL_x=droplevels(as_factor(TPSFAMIL_c))) %>% 
  mutate(TPS=ifelse(TPSAMI_x %in% c("Tous les jours ou presque","Au moins une fois par semaine") |
                              TPSASSO_x %in% c("Tous les jours ou presque","Au moins une fois par semaine") |
                                                        TPSFAMIL_x %in% c("Tous les jours ou presque","Au moins une fois par semaine"),3,ifelse(TPSASSO_x %in% c("Au moins une fois par mois","Moins d'une fois par mois") |
                              TPSAMI_x %in% c("Au moins une fois par mois","Moins d'une fois par mois") |
                                                        TPSFAMIL_x %in% c("Au moins une fois par mois","Moins d'une fois par mois"),2,1))) %>% 
  mutate(TPS=factor(TPS,labels=c("Jamais","Moyen","Beaucoup"))) %>% 
  mutate(taille_ville=as_factor(taille_ville)) %>% 
  mutate(taille_ville=relevel(taille_ville,ref="Tres grande")) %>% 
  mutate(taille_ville2=as_factor(taille_ville2)) %>% 
  mutate(taille_ville2=relevel(taille_ville2,ref="Grande")) %>% 
  mutate(pole=as_factor(pole)) %>% 
  mutate(pole=relevel(pole,ref="Grand pole")) %>% 
  mutate(verre=as_factor(verre)) %>% 
  mutate(verre=relevel(verre,ref="Jamais")) %>% 
  mutate(verre=fct_recode(verre,
                          "Jamais"="Jamais",
                          "1 verre ou plus"="1 verre",
                          "1 verre ou plus"="Plus d'un verre")) %>% 
  mutate(TPS=relevel(TPS,ref="Beaucoup")) %>% 
  mutate(social=as_factor(social)) %>% 
  mutate(PBPATHOL_classe=factor(ifelse(PB_PATHOL<=1,1,2),labels=c("1 au plus","Plus de 1"))) %>% 
  mutate(AVENIR_classe=factor(ifelse(AVENIR<=6,1,2),labels=c("Peu preoccupe","Preoccupe"))) %>% 
  mutate(RISQUE_classe=factor(ifelse(RISQUE<=5,1,2),labels=c("Prudent","Aventureux"))) %>% 
  #Recodage de la variable pole
  mutate(pole=fct_recode(pole,
                         "Grand pole"="Grand pole",
                         "Periurbain-Grand pole"="Periurbain",
                         "Autre"="Rural",
                         "Autre"="Moyen")) %>% 
  mutate(social=fct_recode(social,
                           "Pas"="Pas",
                           "Oui"="Moyen",
                           "Oui"="Beaucoup")) %>% 
  mutate(CSP_cat=fct_recode(CSP_cat,
                            "Ouvrier"="Ouvrier prive",
                            "Ouvrier"="Ouvrier publique",
                            "Cadre"="Cadre publique",
                            "Cadre"="Cadre prive")) %>% 
  mutate(etatsante_score=as.numeric(NOTE)) %>% 
  mutate(revenu_dummy=ifelse(revucinsee_c %in% c("1ere tranche","2eme tranche"),1,0))
```


```{r}
#Suppression des observations avec des donnees manquantes
modeldata_sg5=modeldata %>% filter(!is.na(etasante_g) & DEPAMB>0 & !is.na(age_classe)
                     & !is.na(homme) & !is.na(etude_c) & !is.na(CMU_x)
                     & !is.na(CC_x) & !is.na(CSP_cat) & !is.na(fum_cat) & !is.na(verre) &
                       !is.na(difpayer_c) & !is.na(COUPLE_c) & !is.na(RISQUE_classe) &  !is.na(AVENIR_classe) & !is.na(age_classe) & !is.na(adl_limit) &  !is.na(TPS) &
                       !is.na(PBPATHOL_classe) & !is.na(etatsante_score))

#Log des depenses
modeldata_sg5=modeldata_sg5 %>%
  mutate(LOGDEP=log(DEPAMB)) %>% 
  filter(etasante_g!="0") %>% 
  droplevels()

```


```{r}
testdata=modeldata_sg5 %>% 
  mutate(soc_dummy=ifelse(social=="Oui",1,0)) %>% 
  mutate(couple_dummy=ifelse(COUPLE_c=="Oui",1,0)) %>% 
  mutate(isolement_dummy=ifelse(ISOLEMENT_c=="Oui",1,0)) %>% 
  mutate(etatsante_dummy=ifelse(etasante_g=="Mauvais/Moyen",0,1)) %>% 
  mutate(adl1_dummy=ifelse(adl_limit>=1 & adl_limit<3,1,0)) %>% 
  mutate(adl2_dummy=ifelse(adl_limit>=3,1,0)) %>% 
  mutate(frag1_dummy=ifelse(fragilite_cat=="Pre-fragilite",1,0)) %>% 
  mutate(frag2_dummy=ifelse(fragilite_cat=="Fragilite",1,0)) %>% 
  mutate(pbpathol_dummy=ifelse(PBPATHOL_classe=="Plus de 1",1,0)) %>% 
  mutate(verre2_dummy=ifelse(verre=="1 verre ou plus",1,0)) %>% 
  mutate(csp1_dummy=ifelse(CSP_cat=="Cadre",1,0)) %>% 
  mutate(csp2_dummy=ifelse(CSP_cat=="Independant",1,0)) %>% 
  mutate(csp3_dummy=ifelse(CSP_cat=="Inactif",1,0)) %>% 
  mutate(difpayer_dummy=ifelse(difpayer_c %in% c("Oui (Tres)","Oui"),1,0)) %>% 
  mutate(etude1_dummy=ifelse(etude_c=="Secondaire",1,0)) %>% 
  mutate(etude2_dummy=ifelse(etude_c=="Superieure",1,0)) %>% 
  mutate(fum1_dummy=ifelse(fum_cat=="Moins de 10 cigarettes",1,0)) %>% 
  mutate(fum2_dummy=ifelse(fum_cat=="Plus de 10 cigarettes",1,0)) %>% 
  mutate(fum3_dummy=ifelse(fum_cat=="A arrete de fumer",1,0)) %>% 
  mutate(pole1_dummy=ifelse(pole=="Periurbain-Grand pole",1,0)) %>% 
  mutate(pole2_dummy=ifelse(pole=="Autre",1,0)) %>% 
  mutate(avenir_dummy=ifelse(AVENIR_classe=="Preoccupe",1,0)) %>% 
  mutate(risque_dummy=ifelse(RISQUE_classe=="Aventureux",1,0)) %>% 
  mutate(renonc_dummy=ifelse(renonc_flg_all=="Oui",1,0)) %>% 
  mutate(cc_dummy=ifelse(CC_x=="Oui",1,0)) %>% 
  mutate(cmu_dummy=ifelse(CMU_x=="Oui",1,0)) %>%
  mutate(homme_dummy=ifelse(homme=="Homme",1,0)) %>% 
  mutate(age1_dummy=ifelse(age_classe=="70-74",1,0)) %>% 
  mutate(age2_dummy=ifelse(age_classe=="75-79",1,0)) %>% 
  mutate(age3_dummy=ifelse(age_classe=="80-84",1,0)) %>% 
  mutate(age4_dummy=ifelse(age_classe=="85+",1,0)) %>% 
  mutate(csp1_dummy2=ifelse(CSP_cat %in% c("Cadre","Independant"),1,0)) %>% 
  mutate(csp2_dummy2=ifelse(CSP_cat=="Inactif",1,0)) %>% 
  mutate(verre_dummy2=ifelse(verre=="Jamais",1,0)) %>% 
  mutate(fum_dummy2=ifelse(fum_cat %in% c("Plus de 10 cigarettes"),1,0)) %>% 
  mutate(renonc_dent_dummy=ifelse(RENONC_DENT_c==1,1,0)) %>% 
  mutate(renonc_lunet_dummy=ifelse(RENONC_LUNET_c==1,1,0)) %>% 
  mutate(renonc_cons_dummy=ifelse(RENONC_CONS_c==1,1,0)) %>% 
  mutate(renonc_fin_dummy=ifelse(RENONC_FIN_c==1,1,0)) %>% 
  mutate(renonc_long_dummy=ifelse(RENONC_LONG_c==1,1,0)) %>% 
  mutate(renonc_loin_dummy=ifelse(RENONC_LOIN_c==1,1,0)) %>% 
  mutate(ageclass_dummy=ifelse(age_classe2=="80+",1,0))

 



  
```


```{r,fig.height=12,fig.width=12}
##Calculation of correlations between variables##

#Liste des variables
list_var=c("renonc_dent_dummy","renonc_lunet_dummy","renonc_cons_dummy",
    "renonc_fin_dummy","renonc_long_dummy","renonc_loin_dummy","risque_dummy",
    "avenir_dummy","etatsante_dummy","adl1_dummy","adl2_dummy","frag1_dummy",
    "frag2_dummy","pbpathol_dummy","age1_dummy","age2_dummy","age3_dummy","age4_dummy",
    "cc_dummy","pole1_dummy","pole2_dummy","difpayer_dummy","homme_dummy","etude2_dummy","etatsante_score","soc_dummy","couple_dummy","isolement_dummy","verre2_dummy","csp1_dummy","csp2_dummy","csp3_dummy","etude1_dummy",
    "etude2_dummy","fum1_dummy","fum2_dummy","fum3_dummy","cmu_dummy")

list_var=unique(sort(list_var))


#Liaison entre les variables explicatives
library(questionr)
cramer=matrix(NA,length(list_var),length(list_var))
for (i in (1:length(list_var))){
  for (j in (1:length(list_var)))
  {
    cramer[i,j]=cramer.v(table(testdata[[i]],testdata[[j]]))
  }
}

colnames(cramer)=list_var
rownames(cramer)=list_var

library(corrplot)
old=par(no.readonly = TRUE)
par(omi=c(0.4,0.4,0.4,0.4))
corrplot(cramer,type="upper",tl.srt=45,tl.col="black",diag=F,addCoef.col="black",
         addCoefasPercent=T)
par(old)

```

```{r}

library(lavaan)
#CFA model
#Model 3
cfa.model3<-'

#measurement model
renonc=~ renonc_cons_dummy+
    renonc_fin_dummy+renonc_long_dummy+renonc_loin_dummy
sante=~etatsante_dummy+etatsante_score+pbpathol_dummy+frag2_dummy

#regression
#renonc~sante+pole1_dummy+pole2_dummy+etude2_dummy+cmu_dummy+cc_dummy+couple_dummy+risque_dummy+soc_dummy
#+isolement_dummy+difpayer_dummy
#sante~age1_dummy+age2_dummy+age3_dummy+age4_dummy+homme_dummy+etude2_dummy+fum2_dummy+verre2_dummy+couple_d#ummy+avenir_dummy+risque_dummy
#etude2_dummy~age1_dummy+age2_dummy+age3_dummy+age4_dummy+homme_dummy+verre2_dummy

#correlations residuals
etatsante_dummy~~etatsante_score
#renonc_cons_dummy~~etude2_dummy




'

cfa3<-sem(cfa.model3,data=testdata,std.lv=T,ordered=c("etatsante_dummy","adl1_dummy",
                     "adl2_dummy","frag1_dummy","frag2_dummy","pbpathol_dummy",
                     "csp1_dummy","csp2_dummy","csp3_dummy",
                     "etude1_dummy",
                     "renonc_dummy","renonc_dummy","csp1_dummy2","csp2_dummy2",
                     "fum_dummy2","renonc_dent_dummy","renonc_lunet_dummy","renonc_cons_dummy",
                     "renonc_fin_dummy","renonc_long_dummy","renonc_loin_dummy"))
summary(cfa3,fit.measures=TRUE, standardized=TRUE)
```

```{r}
#CFA model
#Model 4
cfa.model4<-'

#measurement model
renonc=~ renonc_cons_dummy+
    renonc_fin_dummy+renonc_long_dummy+renonc_loin_dummy
sante=~etatsante_dummy+etatsante_score+frag2_dummy

#regression
#renonc~sante+pole1_dummy+pole2_dummy+etude2_dummy+cmu_dummy+cc_dummy+couple_dummy+risque_dummy+soc_dummy
#+isolement_dummy+difpayer_dummy
#sante~age1_dummy+age2_dummy+age3_dummy+age4_dummy+homme_dummy+etude2_dummy+fum2_dummy+verre2_dummy+couple_d#ummy+avenir_dummy+risque_dummy
#etude2_dummy~age1_dummy+age2_dummy+age3_dummy+age4_dummy+homme_dummy+verre2_dummy

#correlations residuals
etatsante_dummy~~etatsante_score
#renonc_cons_dummy~~etude2_dummy




'

cfa4<-sem(cfa.model4,data=testdata,std.lv=T,ordered=c("etatsante_dummy","adl1_dummy",
                     "adl2_dummy","frag1_dummy","frag2_dummy","pbpathol_dummy",
                     "csp1_dummy","csp2_dummy","csp3_dummy",
                     "etude1_dummy",
                     "renonc_dummy","renonc_dummy","csp1_dummy2","csp2_dummy2",
                     "fum_dummy2","renonc_dent_dummy","renonc_lunet_dummy","renonc_cons_dummy",
                     "renonc_fin_dummy","renonc_long_dummy","renonc_loin_dummy"))
summary(cfa4,fit.measures=TRUE, standardized=TRUE)
```


```{r,fig.height=12,fig.width=12}
#Model 6
#Best model#
sem.model6<-'

#measurement model
renonc=~ renonc_cons_dummy+
    renonc_fin_dummy+renonc_long_dummy+renonc_loin_dummy
sante=~etatsante_dummy+etatsante_score+pbpathol_dummy+frag2_dummy

#regression
renonc~sante+soc_dummy+verre2_dummy+isolement_dummy+cc_dummy+difpayer_dummy+homme_dummy+revenu_dummy+etude2_dummy
sante~renonc+ageclass_dummy
cc_dummy~difpayer_dummy+isolement_dummy+homme_dummy+revenu_dummy
LOGDEP~sante+cc_dummy+renonc
revenu_dummy~etude2_dummy+ageclass_dummy
difpayer_dummy~revenu_dummy



#correlations residuals
etatsante_dummy~~etatsante_score
#renonc_long_dummy~~cc_dummy
#LOGDEP~~frag2_dummy
pbpathol_dummy ~~ frag2_dummy
'

sem6=sem(sem.model6,data=testdata,std.lv=T,ordered=c("etatsante_dummy","adl1_dummy",
                     "adl2_dummy","frag1_dummy","frag2_dummy","pbpathol_dummy",
                     "csp1_dummy","csp2_dummy","csp3_dummy",
                     "etude1_dummy",
                     "renonc_dummy","renonc_dummy","csp1_dummy2","csp2_dummy2",
                     "fum_dummy2","renonc_dent_dummy","renonc_lunet_dummy","renonc_cons_dummy",
                     "renonc_fin_dummy","renonc_long_dummy","renonc_loin_dummy","cc_dummy","revenu_dummy",
                     "difpayer_dummy"))
summary(sem6,fit.measures=TRUE, standardized=TRUE)

#mi = modificationIndices(sem6)
#head(mi[order(-mi$mi), ], 10)

```

```{r}
#Model 7
sem.model7<-'

#measurement model
renonc=~ renonc_cons_dummy+
    renonc_fin_dummy+renonc_long_dummy+renonc_loin_dummy
sante=~etatsante_dummy+etatsante_score+pbpathol_dummy+frag2_dummy

#regression
renonc~soc_dummy+verre2_dummy+isolement_dummy+cc_dummy+difpayer_dummy+homme_dummy+revenu_dummy+etude2_dummy
sante~renonc+ageclass_dummy
cc_dummy~difpayer_dummy+isolement_dummy+homme_dummy+revenu_dummy
LOGDEP~sante+cc_dummy+renonc
revenu_dummy~etude2_dummy+ageclass_dummy
difpayer_dummy~revenu_dummy



#correlations residuals
etatsante_dummy~~etatsante_score
#renonc_long_dummy~~cc_dummy
#LOGDEP~~frag2_dummy
pbpathol_dummy ~~ frag2_dummy
'

sem7=sem(sem.model7,data=testdata,std.lv=T,ordered=c("etatsante_dummy","adl1_dummy",
                     "adl2_dummy","frag1_dummy","frag2_dummy","pbpathol_dummy",
                     "csp1_dummy","csp2_dummy","csp3_dummy",
                     "etude1_dummy",
                     "renonc_dummy","renonc_dummy","csp1_dummy2","csp2_dummy2",
                     "fum_dummy2","renonc_dent_dummy","renonc_lunet_dummy","renonc_cons_dummy",
                     "renonc_fin_dummy","renonc_long_dummy","renonc_loin_dummy","cc_dummy","revenu_dummy",
                     "difpayer_dummy"))
summary(sem7,fit.measures=TRUE, standardized=TRUE)

#mi = modificationIndices(sem6)
#head(mi[order(-mi$mi), ], 10)
```

```{r}
#Model 8
#Model 7
sem.model8<-'

#measurement model
renonc=~ renonc_cons_dummy+
    renonc_fin_dummy+renonc_long_dummy+renonc_loin_dummy
sante=~etatsante_dummy+etatsante_score+pbpathol_dummy+frag2_dummy

#regression
renonc~sante+soc_dummy+verre2_dummy+isolement_dummy+cc_dummy+difpayer_dummy+homme_dummy+revenu_dummy+etude2_dummy
sante~ageclass_dummy
cc_dummy~difpayer_dummy+isolement_dummy+homme_dummy+revenu_dummy
LOGDEP~sante+cc_dummy+renonc
revenu_dummy~etude2_dummy+ageclass_dummy
difpayer_dummy~revenu_dummy



#correlations residuals
etatsante_dummy~~etatsante_score
#renonc_long_dummy~~cc_dummy
#LOGDEP~~frag2_dummy
pbpathol_dummy ~~ frag2_dummy
'

sem8=sem(sem.model8,data=testdata,std.lv=T,ordered=c("etatsante_dummy","adl1_dummy",
                     "adl2_dummy","frag1_dummy","frag2_dummy","pbpathol_dummy",
                     "csp1_dummy","csp2_dummy","csp3_dummy",
                     "etude1_dummy",
                     "renonc_dummy","renonc_dummy","csp1_dummy2","csp2_dummy2",
                     "fum_dummy2","renonc_dent_dummy","renonc_lunet_dummy","renonc_cons_dummy",
                     "renonc_fin_dummy","renonc_long_dummy","renonc_loin_dummy","cc_dummy","revenu_dummy",
                     "difpayer_dummy"))
summary(sem8,fit.measures=TRUE, standardized=TRUE)
anova(sem6,sem8)
```

```{r}
#Model 9 (Number of pathologies as observed variable)
sem.model9<-'

#measurement model
renonc=~ renonc_cons_dummy+
    renonc_fin_dummy+renonc_long_dummy+renonc_loin_dummy
sante=~etatsante_dummy+etatsante_score+frag2_dummy

#regression
renonc~sante+soc_dummy+verre2_dummy+isolement_dummy+cc_dummy+difpayer_dummy+homme_dummy+revenu_dummy+etude2_dummy
sante~renonc+ageclass_dummy+pbpathol_dummy
cc_dummy~difpayer_dummy+isolement_dummy+homme_dummy+revenu_dummy
LOGDEP~sante+cc_dummy+renonc+pbpathol_dummy
revenu_dummy~etude2_dummy+ageclass_dummy
pbpathol_dummy~ageclass_dummy
difpayer_dummy~revenu_dummy



#correlations residuals
etatsante_dummy~~etatsante_score
#renonc_long_dummy~~cc_dummy
#LOGDEP~~frag2_dummy
pbpathol_dummy ~~ frag2_dummy
'

sem9=sem(sem.model9,data=testdata,std.lv=T,ordered=c("etatsante_dummy","adl1_dummy",
                     "adl2_dummy","frag1_dummy","frag2_dummy","pbpathol_dummy",
                     "csp1_dummy","csp2_dummy","csp3_dummy",
                     "etude1_dummy",
                     "renonc_dummy","renonc_dummy","csp1_dummy2","csp2_dummy2",
                     "fum_dummy2","renonc_dent_dummy","renonc_lunet_dummy","renonc_cons_dummy",
                     "renonc_fin_dummy","renonc_long_dummy","renonc_loin_dummy","cc_dummy","revenu_dummy"))
summary(sem9,fit.measures=TRUE, standardized=TRUE)

mi = modificationIndices(sem6)
head(mi[order(-mi$mi), ], 10)
```

```{r}
#Model 10
sem.model10<-'

#measurement model
renonc=~ renonc_cons_dummy+
    renonc_fin_dummy+renonc_long_dummy+renonc_loin_dummy
sante=~etatsante_dummy+etatsante_score+frag2_dummy

#regression
renonc~sante+soc_dummy+verre2_dummy+isolement_dummy+cc_dummy+difpayer_dummy+homme_dummy+revenu_dummy+etude2_dummy
sante~renonc+ageclass_dummy+pbpathol_dummy
cc_dummy~difpayer_dummy+isolement_dummy+homme_dummy+revenu_dummy
LOGDEP~sante+cc_dummy+renonc+pbpathol_dummy
revenu_dummy~etude2_dummy+ageclass_dummy
difpayer_dummy~revenu_dummy
pbpathol_dummy~ageclass_dummy



#correlations residuals
etatsante_dummy~~etatsante_score
#renonc_long_dummy~~cc_dummy
#LOGDEP~~frag2_dummy
#pbpathol_dummy ~~ frag2_dummy
'

sem10=sem(sem.model10,data=testdata,std.lv=T,ordered=c("etatsante_dummy","adl1_dummy",
                     "adl2_dummy","frag1_dummy","frag2_dummy","pbpathol_dummy",
                     "csp1_dummy","csp2_dummy","csp3_dummy",
                     "etude1_dummy",
                     "renonc_dummy","renonc_dummy","csp1_dummy2","csp2_dummy2",
                     "fum_dummy2","renonc_dent_dummy","renonc_lunet_dummy","renonc_cons_dummy",
                     "renonc_fin_dummy","renonc_long_dummy","renonc_loin_dummy","cc_dummy","revenu_dummy",
                     "difpayer_dummy"))
summary(sem10,fit.measures=TRUE, standardized=TRUE)

#mi = modificationIndices(sem6)
#head(mi[order(-mi$mi), ], 10)
```

```{r}
#Model 11
sem.model11<-'

#measurement model
renonc=~ renonc_cons_dummy+
    renonc_fin_dummy+renonc_long_dummy+renonc_loin_dummy
sante=~etatsante_dummy+etatsante_score+pbpathol_dummy+frag2_dummy

#regression
renonc~sante+soc_dummy+verre2_dummy+isolement_dummy+cc_dummy+difpayer_dummy+homme_dummy+revenu_dummy+etude2_dummy
sante~renonc+ageclass_dummy
cc_dummy~difpayer_dummy+isolement_dummy+homme_dummy+revenu_dummy
LOGDEP~sante+cc_dummy+renonc+couple_dummy
revenu_dummy~etude2_dummy+couple_dummy
difpayer_dummy~revenu_dummy+ageclass_dummy



#correlations residuals
etatsante_dummy~~etatsante_score
#renonc_long_dummy~~cc_dummy
#LOGDEP~~frag2_dummy
#pbpathol_dummy ~~ frag2_dummy
'

sem11=sem(sem.model11,data=testdata,std.lv=T,ordered=c("etatsante_dummy","adl1_dummy",
                     "adl2_dummy","frag1_dummy","frag2_dummy","pbpathol_dummy",
                     "csp1_dummy","csp2_dummy","csp3_dummy",
                     "etude1_dummy",
                     "renonc_dummy","renonc_dummy","csp1_dummy2","csp2_dummy2",
                     "fum_dummy2","renonc_dent_dummy","renonc_lunet_dummy","renonc_cons_dummy",
                     "renonc_fin_dummy","renonc_long_dummy","renonc_loin_dummy","cc_dummy","revenu_dummy",
                     "difpayer_dummy"))
summary(sem11,fit.measures=TRUE, standardized=TRUE)

#mi = modificationIndices(sem11)
#head(mi[order(-mi$mi), ], 10)
```


```{r,fig.height=12,fig.width=12}
#Importing packages#
library("DiagrammeR")
library("stringr")
library(devEMF)

#Model graph
paths <- sem11 %>%
  standardizedSolution %>%
  select(lhs, op, rhs, est=est.std)

# Latent variables are left-hand side of "=~" lines
latent <- paths %>%
  filter(op == "=~") %>%
  select(nodes = lhs) %>%
  distinct %>%
  mutate(shape = "circle")

# Manifest variables are not latent variables
`%not_in%` <- Negate(`%in%`)
manifest <- sem11 %>%
  standardizedSolution %>% 
  select(lhs, op, rhs, est=est.std) %>% 
  filter(op != "~1", lhs %not_in% latent$nodes) %>%
  select(nodes = lhs) %>%
  distinct %>%
  mutate(shape = "square")

# Nodes are prepared
node_set=latent %>% 
  bind_rows(manifest)

#node_set <- combine_ndfs(latent, manifest)
#node_set

uniquenodes=node_set %>% 
  select(nodes) %>% 
  pull %>% 
  unique

nodes_label=c("Unmet \nneeds","Health","Complementary \n insurance","Healthcare \nexpenditures",
              "Low income","Financial \n difficulties","Self-perceived \nhealth #1","Consultation","Financial \nreason",
              "Delay","Distance","Number of \npathologies","Frailty","Self-perceived \nhealth #2","Social life",
              "Drinking","Experience of\n seclusion","Gender","Education","Age","Married")

#edges
all_paths <- sem11 %>%
  standardizedSolution %>% 
  select(lhs, op, rhs, est=est.std) %>% 
  filter(op != "~1") %>%
  mutate(label = round(est, 2)) %>%
  select(-est)

# Factor loadings are the paths in the "=~" lines
loadings <- all_paths %>%
  filter(op == "=~") %>%
  mutate(edge_from = lhs, edge_to = rhs, style = "dashed") %>%
  select(edge_from, edge_to, style, label)

# Regressions are the paths in the "~" lines
regressions <- all_paths %>%
  filter(op == "~") %>%
  rename(edge_to = lhs, edge_from = rhs) %>%
  mutate(style = "solid") %>%
  select(edge_from, edge_to, style, label) %>% 
  mutate(dir="forward")

#correlations
correlations <- all_paths %>%
  filter(op == "~~") %>%
  rename(edge_to = lhs, edge_from = rhs) %>%
  mutate(style = "solid") %>%
  mutate(dir = "both") %>%
  select(edge_from, edge_to, style, label)

edge_set=loadings %>%
  bind_rows(regressions)
#edge_set <- combine_edfs(loadings, regressions)

nodes <- create_node_df(n=length(uniquenodes), 
         type="number", 
         label=nodes_label,
         shape=node_set$shape) 

edges <- create_edge_df(from=match(edge_set$edge_from, uniquenodes), 
         to=match(edge_set$edge_to, uniquenodes), 
         rel="leading_to",
         label=edge_set$label,
         style=edge_set$style,
         dir=edge_set$dir) 

# Combine edges and nodes
library(magrittr)
my_graph <- create_graph(
  nodes_df = nodes,
  edges_df = edges) %>% 
   add_global_graph_attrs(
      attr = c("layout", "rankdir", "splines","nodesep","fontsize","height"),
      value = c("dot", "LR", "true",0.25,10,0.9),
      attr_type = c("graph", "graph", "graph","graph","edge","node"))
# We can plot the graph directly
render_graph(my_graph) 

#g <- create_graph(nodes_df=nodes, edges_df=edges)
#get_global_graph_attrs(g)
emf(file = "sem.emf", width = 10, height = 10)
render_graph(my_graph) 
dev.off()

```

```{r}
#CFA graph
#Model graph
paths <- cfa3 %>%
  standardizedSolution %>%
  select(lhs, op, rhs, est=est.std)

# Latent variables are left-hand side of "=~" lines
latent <- paths %>%
  filter(op == "=~") %>%
  select(nodes = lhs) %>%
  distinct %>%
  mutate(shape = "circle")

# Manifest variables are not latent variables
`%not_in%` <- Negate(`%in%`)
manifest <- cfa3 %>%
  standardizedSolution %>% 
  select(lhs, op, rhs, est=est.std) %>% 
  filter(op != "~1", lhs %not_in% latent$nodes) %>%
  select(nodes = lhs) %>%
  distinct %>%
  mutate(shape = "square")

# Nodes are prepared
node_set=latent %>% 
  bind_rows(manifest)

#node_set <- combine_ndfs(latent, manifest)
#node_set

uniquenodes=node_set %>% 
  select(nodes) %>% 
  pull %>% 
  unique

nodes_label=c("Unmet \nneeds","Health","Self-perceived \nhealth #1","Consultation","Financial \nreason",
              "Delay","Distance","Number of \npathologies","Frailty","Self-perceived \nhealth #2")

#edges
all_paths <- cfa3 %>%
  standardizedSolution %>% 
  select(lhs, op, rhs, est=est.std) %>% 
  filter(op != "~1") %>%
  mutate(label = round(est, 2)) %>%
  select(-est)

# Factor loadings are the paths in the "=~" lines
loadings <- all_paths %>%
  filter(op == "=~") %>%
  mutate(edge_from = lhs, edge_to = rhs, style = "dashed") %>%
  select(edge_from, edge_to, style, label)

# Regressions are the paths in the "~" lines
regressions <- all_paths %>%
  filter(op == "~") %>%
  rename(edge_to = lhs, edge_from = rhs) %>%
  mutate(style = "solid") %>%
  select(edge_from, edge_to, style, label) %>% 
  mutate(dir="forward")

#correlations
correlations <- all_paths %>%
  filter(op == "~~") %>%
  rename(edge_to = lhs, edge_from = rhs) %>%
  mutate(style = "solid") %>%
  mutate(dir = "both") %>%
  select(edge_from, edge_to, style, label,dir)

edge_set=loadings %>%
  bind_rows(regressions) %>% 
  bind_rows(correlations)
#edge_set <- combine_edfs(loadings, regressions)

nodes <- create_node_df(n=length(uniquenodes), 
         type="number", 
         label=nodes_label,
         shape=node_set$shape) 

edges <- create_edge_df(from=match(edge_set$edge_from, uniquenodes), 
         to=match(edge_set$edge_to, uniquenodes), 
         rel="leading_to",
         label=edge_set$label,
         style=edge_set$style,
         dir=edge_set$dir) 

# Combine edges and nodes
library(magrittr)
my_graph <- create_graph(
  nodes_df = nodes,
  edges_df = edges) %>% 
   add_global_graph_attrs(
      attr = c("layout", "rankdir", "splines","nodesep","fontsize","height"),
      value = c("dot", "LR", "true",0.25,10,0.9),
      attr_type = c("graph", "graph", "graph","graph","edge","node"))
# We can plot the graph directly
render_graph(my_graph) 

#g <- create_graph(nodes_df=nodes, edges_df=edges)
#get_global_graph_attrs(g)
emf(file = "cfa.emf", width = 6, height = 10)
render_graph(my_graph) 
dev.off()
```




